name: Build Docker base images

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build_docker_base_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile_base, Dockerfile_base_test]
        dockerfiletest: [Dockerfile_rel, Dockerfile_rel_test]
        tag: [signalk/signalk-server-base, signalk/signalk-server-base-test]
        ghcr_tag: [ghcr.io/signalk/signalk-server-base, ghcr.io/signalk/signalk-server-base-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: signalkci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Personal access tokens (classic) with a scope of "write:packages" is needed to release ghcr.io package registry. 

      - name: Copy Dockerfile_base and modify Dockerfile_base_test
        run: |
          cp ./docker/Dockerfile_base ./docker/Dockerfile_base_test
          sed -i 's|FROM ubuntu:22.04|FROM ubuntu:24.04|' Dockerfile_base_test
          sed -i '1a RUN userdel -r ubuntu' Dockerfile_base_test
          sed -i 's|python2 ||' Dockerfile_base_test
          sed -i 's|groupadd -r docker -g 998|groupadd -r docker -g 991|' Dockerfile_base_test
          sed -i 's|groupadd -r i2c -g 997|groupadd -r i2c -g 990|' Dockerfile_base_test
          sed -i 's|groupadd -r spi -g 999|groupadd -r spi -g 989|' Dockerfile_base_test

      - name: Build baseimages and push with test tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ matrix.tag }}:test
            ${{ matrix.ghcr_tag }}:test

      - name: Modify Dockerfile_rel and Dockerfile_rel_test for testing
        run: |
          cp ./docker/Dockerfile_rel ./docker/Dockerfile_rel_test
          sed -i \
          's|FROM cr.signalk.io/signalk/signalk-server-base:latest|FROM cr.signalk.io/signalk/signalk-server-base:test|' \
          ./docker/Dockerfile_rel
          sed -i \
          's|FROM cr.signalk.io/signalk/signalk-server-base:latest|FROM cr.signalk.io/signalk/signalk-server-base-test:test|' \
          ./docker/Dockerfile_rel_test
          
      - name: Build Signal K test images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.dockerfiletest }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            TAG=latest

      - name: Push baseimages to registries with latest tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ matrix.tag }}:latest
            ${{ matrix.ghcr_tag }}:latest
